apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-monitor
  namespace: iris
  labels:
    app: ml-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-monitor
  template:
    metadata:
      labels:
        app: ml-monitor
    spec:
      containers:
      - name: ml-monitor
        image: gilsama/ml_monitor:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ml-monitor
  namespace: iris
spec:
  selector:
    app: ml-monitor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: LoadBalancer