database_name: "default"
feature_table_name: "airbnb_feature_table"
feature_table_path: "dbfs:/mnt/feature_tables/airbnb/"
source_data: "dbfs:/FileStore/datasets/airbnb/listings.csv"
columns_to_keep:
    - "id"
    - "host_is_superhost"
    - "instant_bookable"
    - "host_total_listings_count"
    - "neighbourhood_cleansed"
    - "latitude"
    - "longitude"
    - "property_type"
    - "room_type"
    - "accommodates"
    - "bedrooms"
    - "beds"
    - "minimum_nights"
    - "number_of_reviews"
    - "review_scores_rating"
    - "review_scores_accuracy"
    - "review_scores_cleanliness"
    - "review_scores_checkin"
    - "review_scores_communication"
    - "review_scores_location"
    - "review_scores_value"
    - "price"
