services:
  redis:
    image: redis:6.0.7
    container_name: redis 
    restart: always 
    volumes:
      - redis_volume_data:/data
    ports:
      - "6379:6379"

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "8003:8003"
    volumes:
      - redis_insight_volume_data:/db

  ml_service1:
    build: ./ml_service1

  ml_service2:
    build: ./ml_service2

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - ml_service1
      - ml_service2

volumes:
  redis_volume_data:
  redis_insight_volume_data: