build:
  no_build: true
environments:
  default:
    workflows:
      - name: "feature_preparation"
        spark_python_task:
          python_file: "file://feature_preparation.py"
      - name: "training"
        spark_python_task:
          python_file: "file://model_training.py"          
      - name: "inferencing"
        spark_python_task:
          python_file: "file://model_inference.py"           
      - name: "transition_model"
        spark_python_task:
          python_file: "file://transition_model.py"                     