mlflow:
  experiment_name: bike_sharing_optimization
  run_name: optimizing
  artifact_path: RandomForestRegressor
  tags:
    project_name: bike_sharing
    model: random_forest_regressor
    task: regression
    