services:
  tracking_service:
    image: ghcr.io/mlflow/mlflow:v2.20.1
    ports:
      - "5000:5000"
    environment:
      MLFLOW_BACKEND_STORE_URI : "sqlite:///mlflow/backend/mlflow.db"
      MLFLOW_HOST : "0.0.0.0"
      MLFLOW_PORT : "5000"
    volumes:
      - mlflow-backend-store:/mlflow/backend/
    command: ["mlflow", "server"]

  train_service:
    build:
      context: .
      dockerfile: train_service/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - tracking_service


volumes:
  mlflow-backend-store: