services:
  irisclassifier:
    build: ./iris_classifier
    expose:
      - 5000
    environment:
      - MODE=SCORE
  # mlapp:
  #   build: ./ml_app
  #   expose:
  #     - 5000
    
    
  monitoringapp: 
    build: ./monitor_app
    ports:
    - 8501:8501
    