apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-monitor
  namespace: iris
  labels:
    app: ml-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-monitor
  template:
    metadata:
      labels:
        app: ml-monitor
    spec:
      containers:
      - name: ml-monitor
        image: gilsama/ml_monitor:latest
        ports:
        - containerPort: 8501
        env:
        - name: TARGET_SERVICE
          value: "IRIS"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ml-monitor
  namespace: iris
spec:
  selector:
    app: ml-monitor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8501
  type: LoadBalancer